### ISSUE TITLE
Create Wallet Developers Guide

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony#1354]
**Overview**
Harmony needs application wallets in order to allow end users to sign transactions and transfer tokens.
Wallet Providers are looking for documentation as to how to build on Harmony.
This guide is a critical piece of information for them.
Creating this guide will also serve to validate existing API's, identify gaps and test BetaNet

**Background Information**
Eric Yu from Math Wallet has asked for the following information
```
@John Whitton Hi John, I would suggest your team or community can prepare below 2 component (use zilliqa as example)
1- JS library https://github.com/Zilliqa/Zilliqa-JavaScript-Library
2- RPC doc https://apidocs.zilliqa.com/#introduction
```
* Work has started on an [SDK-WIKI](https://app.gitbook.com/@harmony-one/s/sdk-wiki/) and is available [here](https://docs.harmony.one/sdk-wiki/)
* Also a postman library has been created for Harmony and can be joined [here](https://app.getpostman.com/join-team?invite_code=272e00328f36deefb4f9e751b6f34a79)
* Harmony GoDocs can be found [here](https://godoc.org/github.com/harmony-one/harmony/hmy#APIBackend.GetBalance)
* API's are [documented in the sdk](https://github.com/harmony-one/sdk/blob/master/packages/harmony-network/src/rpcMethod/rpc.ts) and [implemented in harmony](https://github.com/harmony-one/harmony/blob/master/hmy/api_backend.go)

**Tasks**
- [x] Document all API's which are [documented in the sdk](https://github.com/harmony-one/sdk/blob/master/packages/harmony-network/src/rpcMethod/rpc.ts) and [implemented in harmony](https://github.com/harmony-one/harmony/blob/master/hmy/api_backend.go)
- [x] Raise tickets for any issues and resolve them
- [x] Ensure [Web Wallet](https://github.com/harmony-one/dapp-examples/tree/master/web/WebWallet) is working as expected in BetaNet 
- [x] Publish the Wiki
- [x] Share the Wiki with a partner

**Acceptance Criteria**
- [x] All API's are documented and reviewed by an engineering team member
- [x] All Issues are resolved
- [x] Web Wallet is deployed locally and works for Betanet
- [x] Hosted Web Wallet is deployed for BetaNet
- [x] Document is shared with at least one development partner
- [x] Documentation is published and shared via social Media

**Comment by john-harmony** [comment]
Closing this as all this has been published. Will track issues for Math Wallet and postman documentation separately.
