### ISSUE TITLE
Firestack - Math Wallet Requirements

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony#1453]
**Following is a request from Michael at Firestack**

Here are what i need from @minh@harmony.one:

- [x] 1. provides stable local node to test, and tell me how to get test accounts' private key
- [x] 2. provides the hmy_getShardingStructure api with correct format that returns.
- [x] 3. provides local nodes with the cross-shard feature enabled

Futher, I also need:
- [x] 4. BetaNet with the features above merged
- [x] 5. BetaNet with cross-shard enabled
- [x] 6. BetaNet test account which have some tokens

Point 1-3 allows me to fully debug the current sdk.
Point 4-6 allows mathWallet to test their feature without running local node

**Comment by john-harmony** [comment]
So just looking at your request above.
Useful information is [here](https://docs.harmony.one/sdk-wiki/api-developers-guide/overview) 
1. Per the guide you should use  http://l0.b.hmny.io:9500 (right now it's up) 
[Account](https://docs.harmony.one/sdk-wiki/developers/local-harmony-web-wallet/setting-up-your-accounts) - one18t4yj4fuutj83uwqckkvxp9gfa0568uc48ggj7
[Private Key](https://docs.harmony.one/sdk-wiki/developers/local-harmony-web-wallet/funding-your-wallet) - 01F903CE0C960FF3A9E68E80FF5FFC344358D80CE1C221C3F9711AF07F83A3BD

Currently it has about 200 ONE in it.

**Comment by mikedoan** [comment]
1. 2. 3. done by https://github.com/harmony-one/harmony/pull/1440

I'm working on 4.5.6 now.

**Comment by john-harmony** [comment]
Review of MathWallet Feedback
0 - Use drop downs instead of shard suffix for cross-shard
1 - Cannot support multiple accounts from the same account phrase
2 - Usually Math Wallet does not show the transaction hash - Michael is suggesting confirmation shows transaction hash (cannot add text on confirmation screen)
3 - They can show an explorer link, if we provide a txn history api, they can use that, they don't store txn history locally
4. - Michael will confirm if MathWallet can subscribe to blocks or listen for transaction confirmation

**Comment by john-harmony** [comment]
Mainnet URL - 
Google takes 3 working days (or more) to add a chrome extension
- [ ] Michael would like a small amount of tokens to test on Mainnet
- [ ] Michael would like the explorer URL to look up a transaction history
