### ISSUE TITLE
Mainnet V1 - Migration Checklist

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony#1556]
# Mainnet V1 - Release Checklist

Following are some tests to be completed for Mainnet V1

**Code Complete**
- [x]  [HTTPs support](https://github.com/harmony-one/harmony/blob/master/internal/configs/sharding/testnet.go#L143)
   - [x] hmy_getShardingStructure - Reflect new https DNS entries e.g.  https://api.s1.b.hmny.io/
   - [x] Websocket and RPC/API support for HTTPS
- [ ] Default Shard ID - @mikedoan | Harmony 
  - [ ] Return the default shard ID to SDK when calling hmy_getShardingStructure

- [x] [Explorer Issue](https://github.com/harmony-one/harmony/issues/1555) - not parsing blocks greater than 77

**Merge any outstanding Pull Requests**
 - [x] [Header Validation](https://github.com/harmony-one/harmony/pull/1539)

**Betanet Upgrade**
- [x] Decision on  whether to test S3 upgrade path @LeoHChen @harmony-ek @rlan35 
- [x] Upgrade Betanet to Master - @charleszqwang @AndyBoWu 
- [x]  Successful transaction testing - @chaosma @fxfactorial @johnwhitton 
- [ ]  MathWallet Validation - @johnwhitton 
- [ ] Explorer Validation - @flicker-harmony 
- [x]  RPC/API Testing - @mikedoan @john-harmony 
- [ ] Negative use case tests - (Transactions sent under adverse conditions) @chaosma @denniswon @harmony-ek 
  - [ ]  Beacon chain not synching
  - [ ] Conensus on 1 shard only
  - [ ] Test when one or more nodes are down for DNS entry
- [x] Transactions Throttling Tests @denniswon 
- [ ] Stress Testing @fxfactorial @denniswon @chaosma 
  - [ ] Send Number of txns to test txns per block and pooling (hmy_cli)
- [ ] Cross Shard
  - [ ] Test recovery process
  - [x] Test sending transactions from one shard to another 

- [ ] **Yes or No Decision on Mainnet V1 Launch**

- [ ] **Mainnet Upgrade and Validation**

**Comment by john-harmony** [comment]
**From @denniswon**
 Transactions Throttling Tests
* Stress Testing
  * Send Number of txns to test txns per block and pooling (hmy_cli)
* Cross Shard
  * Test recovery process
  * Test sending transactions from one shard to another 

Conducted yesterday: 
Cases tested (single & cross-shard txn):
1. max txn limit throttling (txn gets invalidated on throttle) - check
2. max number of txns per account per hour (txn gets invalidated on throttle) - check
3. account nonce check on each txn (i.e. each successful txn incrementing nonce before being able to accept the next txn)
4. sending some edge case amounts (one account, moving funds from one shard to another, sending 0 ONE txn, over-balance txn, etc.)
5. multiple wallets/accounts testing

1~4 tested on localnet. 5 on betanet by @chao | Harmony 

cc: @Rongjian Lan | Harmony @Eugene Kim | Harmony Testing was conducted with the new v2 header. Have not tested the compatibility/handling of v1 vs v2, header cases.

cc:: @Leo | Harmony

**Comment by john-harmony** [comment]
Issues found (and resolved) when testing
- [ ] Betanet Explorer 1 was not working (upgraded software and still synching)
- [ ] Mainnet cross shards not working (cross shard was not set up for mainnet)
- [ ] Betanet Same shard 0 to 0 volume testing https://api.s0.b.hmny.io - error TLS not connecting
- [ ] Transaction HIstory - does not show all transactions -  http://e0.b.hmny.io:5000/address?id=one1shzkj8tty2wu230wsjc7lp9xqkwhch2ea7sjhc&tx_view=ALL 
- [ ] Wallet Keys need to be setup

**Comment by john-harmony** [comment]
This work is now being complete in an internal gitbook.
