### ISSUE TITLE
explorer todo

### ISSUE THREAD

**Issue by lzl124631x** [harmony-one/harmony#162]
@mikedoan 

- [x] timestamp as number
- [x] height as number
- [x] txCount as number
- [x] api `/address`
- [x] fix bug: `nextBlock` missing
