### ISSUE TITLE
CLI Overhaul release plan

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3285]
## Description

PR #3278 is to overhaul the harmony CLI. This PR will break the backward compatibility of node.sh running new harmony CLI interface, so we need to carefully process the transition.

## Prerequisites

- [x] Confirm with Leo to determine whether this is a good time to start. (Now would be a good time to start).
- [x]  Confirm with Leo about the release version strategy. （Version is not critical for this release)
- [x]  [Confirm with Daniel](https://github.com/harmony-one/harmony/issues/3287) whether Autonode is included in this scope and how should it be engaged.

## Resources

1. [Pull request](https://github.com/harmony-one/harmony/pull/3278): Code of the upcoming changes.
2. [CLI Interface introduction](https://gist.github.com/JackyWYX/f2052c15a05dad63ea9555af02fe5bfa#file-introduction-md): Three documents included
   * A brief introduction to how to run harmony node with CLI interface
   * An in-depth explanation on the certain topics
   * All hidden and legacy flags
3. [Release plan](https://github.com/harmony-one/harmony/issues/3285): Release plan by far. Not final version, will update over time.
4. [Acquire binary and node.sh for test](https://gist.github.com/JackyWYX/17679f124b5f3dd8e1a6975b41bdeee6)

## What flow is going to be after release

1. Download binary from `https://www.harmony.one/binary`
2. Put BLS keys to folder `.hmy/blskeys`. (If already set, no need to do again)
3. Run mainnet node with `./harmony`. 

## Participants and responsibilities

* Jacky: 
  * Dev support for harmony binary and node.sh
  * Organizer of this release.
* Leo:
  * Handle repository related issues.
  * Handle all mainnet deployment issues.
* POPS: 
  * Study and test new CLI interface
  * Tech support for foundation nodes
* yellowsin: 
  * Prepare harmony runbook documentations
* Daniel & Janet:
  * Autonode development, testing and deployment
  * Tech support for auto node.
  * go-sdk dev support

## Release steps

The release step is composed of three phases:

1. Dev build and test
2. Internal release and testing. (7 days)
3. Public release transitioning. (7~ days)

### 1. Dev build and test 

- [x] 1.1 Rebase the PR on main (Jacky)
- [x] 1.2 Apply code changes (Jacky)
  * In node.sh, update the version.
  * In node.sh, update the bucket logic, default to use a new folder `main_v2` as master.
- [x] 1.3 Build and release to S3 with name `main_v2` (Jacky)
- [x] 1.4 [Do all tests on the rebased branch](https://github.com/harmony-one/harmony/issues/3290).  (Jacky)
  * Rerun previous tests ([Test log1](https://gist.github.com/JackyWYX/2554d561ccca74617d68a74a53ca64e3), [Test log 2](https://gist.github.com/JackyWYX/adae08dd1984a2943c10a5358aa4b59a#file-testlog-md), [Test log 3](https://gist.github.com/JackyWYX/adae08dd1984a2943c10a5358aa4b59a#file-another-test-md)) (Jacky)
  * Stressnet test. Shall go smooth without interruption (Jacky)
- [x] 1.5 Autonode code change and test (Daniel & Janet)

### 2. Internal release

Time estimated for this phase is about 5 days. 

- [x] 2.1 Merge the branch to main. Nightly build and test on Testnet. (Leo)
- [x] 2.2 Release the binary in step 1 to internal POPS teams (Jacky)
- [x] 2.3 The binary can be also be shared to some of our foundation nodes to collect feedbacks (POPS team)
- [x] 2.4 According to the new CLI interface, [update the Harmony runbook](https://github.com/harmony-one/harmony/issues/3286) (yelllowsin)
- [x] 2.5 According to [feedbacks](https://github.com/harmony-one/harmony/issues/3298) from POPS team, update the binary (Jacky)

### 3. Public release

Will need 7 days or even more for our foundation nodes transitioning to new node.sh or directly running command line.

- [x] 3.0 Use Jenkins to release the branch to s3 folder main_v2 (Leo)
- [x] 3.1 Update `harmony.one/node.sh` and `harmony.one/binary` website link with Li (Jacky)
- [x] 3.2 Announce the CLI interface change to our foundation nodes (Leo, POPS, Maggie)
- [x] 3.3 Use Ansible to release the binary to our mainnet nodes. (Leo)
- [x] 3.4 Autonode release and dev support (Daniel & Janet)
- [x] 3.5 Publish updates on validator runbook.
- [ ] 3.6 Q&A and tech support for foundation nodes with new CLI (Jacky, POPS, Daniel, Janet)

## Timeline

All time here is in time zone PDT.

Phase 1 Dev build and test: 8/10-8/12
Phase 2 Internal release: 8/12-8/16
Phase 3 External release: 8/17-8/23

## Out of scope

1. Website download endpoint with Github release.

####  Remove dependency on node.sh on all projects
  * Autonode and implement auto-update logic.
  * All systemd commands
  * Totally not in hurry. Very long term

#### `harmony.one` download page (E.g https://geth.ethereum.org/downloads/)
  * Can download all history versions
  * Integration with Github release?

**Comment by LeoHChen** [comment]
* Autonode has to supported.  I saw ppl using it.  So, let's get @janet-harmony involved to evaluate and test on autonode support.
* For internal, if we merged it and the code will be deployed to testnet on a nightly basis.  So we have good coverage already.  internal can be shorten to 3 days.
* External is more like educational.  Most of the people are using our node.sh wrapper or autonode, so that's less concern if all the cli options are still valid.

**Comment by JackyWYX** [comment]
I definitely agree with shortening internal release to 3 days. My intention of internal release is to 

1. let our POPS team get familiar with our new CLI interface and gather feedbacks. 
2. Yellowsin can finish the node [running doc](https://docs.harmony.one/home/validators/first-time-setup) as well as the migration plan. 

So the timeline seems can be the following if internal release takes 3 days: 
1. I can rebase, do updates , test again in two days (By 8/11). 
2. Internal release starts on 8/12 and closes on Friday 8/14. 
3. Public release on 8/15 - 8/22. (Saturday is a good time for release?)
4 8/23 Clean and merge.

We have 2 X factors now:

1. Yellowsin's estimation on updating docs.
2. Autonode's support by Daniel and Janet.

We can confirm these two factors and fix the final timeline. Seems good to you? @LeoHChen

**Comment by LeoHChen** [comment]
We don't usually do public release over the weekend.  Monday is better. For internal release, the code has to be merged, so that we can find problem in testnet.

**Comment by LeoHChen** [comment]
So, I recommend merge to main branch on 8/12 or 8/13.

**Comment by sophoah** [comment]
@JackyWYX I would suggest you give POPS maybe 1 week so we can test and be familiarize with the new node.sh via a private release of the binary, once validated then you can release to the public, what do you think ?

**Comment by JackyWYX** [comment]
> @JackyWYX I would suggest you give POPS maybe 1 week so we can test and be familiarize with the new node.sh via a private release of the binary, once validated then you can release to the public, what do you think ?

@LeoHChen Does this sound good to you?

**Comment by LeoHChen** [comment]
@sophoah , the node.sh is fully compatible with the old one, so no need to wait for 1 week.   The main update is the harmony binary itself with different command line option format, but they are wrapped nicely in the original option of node.sh.  So, I don't think we need another week.  What do you think?

**Comment by LeoHChen** [comment]
@sophoah would 3 days okay for you?

**Comment by yelllowsin** [comment]
Hey @JackyWYX here is the initial version of the documentation: https://docs.harmony.one/home/validators/under-construction
I haven't added instructions for Tmux yet, but we could add these as well.
