### ISSUE TITLE
[build] official release package in deb and rpm format

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3305]
## Summary

We are using a customized release package so far.
We have to build many customized deployment script and configuration scripts around it for validators.

To facilitate the installation and upgrade process, we need to build the format of the standard package using Deb or RPM packages.
Standard packages have many advantages like detailed documentation, many supporting tooling, easy integration, and lower learning curve.

## TODO
- [x] build rpm package
- [x] build deb package
- [x] sign package using official pgp signature
- [x] automate the version/changelog of the package
- [x] release package in public repo for rpm/deb
- [x] testing plan document
- [x] publish and update repo process need more test and automation
- [x] test by p-ops
- [x] test by validators
- [ ] autonode support
- [ ] updated ansible script, work with Blockdaemon: https://github.com/Blockdaemon/harmony-deploy
- [ ] update jenkins release job to build/sign/publish rpm/deb package
- [ ] official document for the standard package installation/upgrade
- [x] release to public

**Comment by mindstyle85** [comment]
what happens if youre already on systemd and on a non root user, but youre using a different user than this package suggests (harmony)? will it override everything or will it check if any existing users are there/and possible systemd files?

**Comment by LeoHChen** [comment]
I'd suggest setting up a new host for the new package.

**Comment by LeoHChen** [comment]
RPM and DEB packages are built during release process.
