### ISSUE TITLE
PBFT todo

### ISSUE THREAD

**Issue by chaosma** [harmony-one/harmony#877]
- [x] test leader offline with m2 type view change message (i.e. prepared message is NIL) [876](https://github.com/harmony-one/harmony/pull/876)
- [x] test leader offline with m1 type view change message( i.e. prepared message is not nil) [945](https://github.com/harmony-one/harmony/pull/945)
- [x] test leader offline with m1 and m2 type view change
- [x] add viewID/blockHash signature on viewchange messages for new leader [945](https://github.com/harmony-one/harmony/pull/945)
- [x] accept normal message in view change mode to escape view change trap [933](https://github.com/harmony-one/harmony/pull/933)
- [x] change 3 timeouts in normal mode to 1 timeouts [#919](https://github.com/harmony-one/harmony/pull/919)
- [x] integrate with state syncing [902](https://github.com/harmony-one/harmony/pull/902)
- [x] change format of commit message to |blockNum|blockHash|signature|. two purposes: avoid leader prepared signature attack,  new node can verify easily [978](https://github.com/harmony-one/harmony/pull/978)
- [x] move the prepared/committed signatures to beginning of block proposal [1124](https://github.com/harmony-one/harmony/pull/1124)
- [x] new node identify leader and viewID [1176](https://github.com/harmony-one/harmony/pull/1176)
- [ ] view change viewID stability: when validators have different viewIDs, how to quickly sync up with each other. e.g. when n/3 nodes offline and online after a while
- [x] add 2f+1 signature checking [972](https://github.com/harmony-one/harmony/pull/972)
- [x] accept newer prepared message and remove older view prepared message
- [x] view change trapped nodes back logic
- [ ] unify the role of leader and validator of the node configuration
- [ ] add clean logic for pending txs when node is not leader
- [ ] add malicious node configuration to simulate different scenarios

**Comment by chaosma** [comment]
integrate with state syncing: [#902](https://github.com/harmony-one/harmony/pull/902) This is a quick fix for unblocking our current progress. In future, we need to work a more stable design. 
see issue: [#903](https://github.com/harmony-one/harmony/issues/903)
as well as my in progress but not working yet PR: [#899](https://github.com/harmony-one/harmony/pull/899)
